-- Making the migration files say what the database already does.
--
-- 0035 widened nine role gates by REWRITING function bodies in place: it read
-- each definition out of pg_proc, replaced `role = 'teacher'` with the three
-- staff roles, and re-executed it. That was a deliberate choice, and its
-- reasoning was sound —
--
--   "Copying them out of older migrations would silently revert whatever later
--    migrations changed ... and that class of mistake is exactly what this
--    migration exists to fix."
--
-- It avoided that mistake and created a quieter one. The files on disk were
-- never updated, so six of them now describe a database that does not exist.
-- Anyone reading them — or replaying them into a fresh environment — gets the
-- narrow gate back, and the symptom is the one 0035 itself describes: the page
-- opens and every panel on it is empty, because an empty result is not an
-- error.
--
-- It came within one line of happening twice today. 0049 and 0051 both had to
-- re-declare functions whose newest file still said `role = 'teacher'`, and
-- both were caught only because the drift was already known about. The next
-- person will not know.
--
-- So this writes the six out properly. Each body below is the newest definition
-- from its own file with exactly the substitution 0035 performed — generated by
-- script from those files rather than retyped, so nothing else can have changed
-- on the way. Replaying the migrations from empty now produces the database
-- that exists.
--
-- Verified before writing: all four readable ones return rows to a principal
-- today, which is only possible if 0035 widened them. 0035 also ends by raising
-- unless zero functions still carry the old predicate, so its success is itself
-- proof that every one of these was rewritten.
--
-- NOTHING CHANGES HERE. This migration is a no-op against the live database by
-- construction: it re-issues definitions identical to what is already there.
-- Its whole purpose is the files.
--
-- The lesson, for whoever writes the next one: a migration that discovers what
-- to change by reading the catalogue leaves no record of what it changed.
-- Prefer writing the new definition out, even when that means repeating a
-- hundred lines. There is a test beside these files now (supabase/gates.test.ts)
-- that fails if any function's newest definition carries the old predicate.

-- public.rotate_class_code — newest definition is 0016_class_join_codes.sql, which predates 0035.
create or replace function public.rotate_class_code(p_class_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_teacher uuid;
  v_code text;
  v_attempt int := 0;
begin
  select cl.teacher_id into v_teacher
  from public.classes cl
  join public.users u on u.id = auth.uid() and u.role in ('teacher', 'hod', 'principal')
  where cl.id = p_class_id;

  -- A teacher may only issue codes for their own sections. Without this, any
  -- teacher could mint a code into a colleague's class and enrol students
  -- into material that isn't theirs.
  if v_teacher is null or v_teacher <> auth.uid() then
    return jsonb_build_object('error', 'That class is not yours.');
  end if;

  update public.class_join_codes
  set revoked_at = now()
  where class_id = p_class_id and revoked_at is null;

  -- Collisions are vanishingly unlikely but not impossible, and the primary
  -- key would raise rather than retry on its own.
  loop
    v_attempt := v_attempt + 1;
    v_code := public.generate_join_code();
    begin
      insert into public.class_join_codes (code, class_id, created_by)
      values (v_code, p_class_id, auth.uid());
      exit;
    exception when unique_violation then
      if v_attempt >= 5 then
        return jsonb_build_object('error', 'Could not create a code. Please try again.');
      end if;
    end;
  end loop;

  return jsonb_build_object('code', v_code);
end;
$$;
revoke all on function public.rotate_class_code(uuid) from public, anon;
grant execute on function public.rotate_class_code(uuid) to authenticated;

-- public.school_analytics — newest definition is 0015_analytics.sql, which predates 0035.
create or replace function public.school_analytics()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select id, school_id from public.users
    where id = auth.uid() and role in ('hod', 'principal')
  ),
  staff as (
    select u.id, u.display_name
    from public.users u, me
    where u.school_id = me.school_id and u.role in ('teacher', 'hod', 'principal')
  ),
  docs as (
    select d.*
    from public.corpus_documents d
    where d.uploaded_by in (select id from staff) and d.superseded_at is null
  ),
  -- Every section in the school, with whether approved material reaches it.
  -- This is the coverage question: not "how much have we uploaded" but "how
  -- many classes have something".
  coverage as (
    select
      co.subject,
      co.grade,
      cl.id as class_id,
      exists (
        select 1
        from public.corpus_document_sections s
        join docs d2 on d2.id = s.document_id
        where s.class_id = cl.id and d2.status = 'approved'
      ) as covered
    from public.classes cl
    join public.courses co on co.id = cl.course_id
    join me on me.school_id = cl.school_id
  )
  select jsonb_build_object(
    'teachers', jsonb_build_object(
      'total', (select count(*) from staff),
      'contributing', (
        select count(distinct d.uploaded_by) from docs d where d.status = 'approved'
      )
    ),
    'documents', jsonb_build_object(
      'approved', (select count(*) from docs where status = 'approved'),
      'pending',  (select count(*) from docs where status = 'pending')
    ),
    'questionsPending', (
      select count(*) from public.generated_questions q
      join public.corpus_chunks c on c.id = q.chunk_id
      where c.document_id in (select id from docs) and q.status = 'pending'
    ),
    'coverage', coalesce((
      select jsonb_agg(jsonb_build_object(
        'subject', subject, 'grade', grade, 'sections', total, 'covered', covered
      ) order by subject, grade)
      from (
        select subject, grade, count(*)::int as total, count(*) filter (where covered)::int as covered
        from coverage group by subject, grade
      ) c
    ), '[]'::jsonb),
    'byTeacher', coalesce((
      select jsonb_agg(jsonb_build_object(
        'name', coalesce(s.display_name, 'Unnamed teacher'),
        'approved', (select count(*) from docs d where d.uploaded_by = s.id and d.status = 'approved'),
        'pending', (select count(*) from docs d where d.uploaded_by = s.id and d.status = 'pending')
      ) order by (select count(*) from docs d where d.uploaded_by = s.id and d.status = 'approved') desc)
      from staff s
    ), '[]'::jsonb),
    'weekly', coalesce((
      select jsonb_agg(jsonb_build_object('week', to_char(w.week, 'YYYY-MM-DD'), 'count',
        (select count(*) from docs d where date_trunc('week', d.created_at) = w.week)::int
      ) order by w.week)
      from (
        select generate_series(
          date_trunc('week', now()) - interval '11 weeks',
          date_trunc('week', now()),
          interval '1 week'
        ) as week
      ) w
    ), '[]'::jsonb)
  )
  where exists (select 1 from me);
$$;
revoke all on function public.school_analytics() from public, anon;
grant execute on function public.school_analytics() to authenticated;

-- public.teacher_analytics — newest definition is 0015_analytics.sql, which predates 0035.
create or replace function public.teacher_analytics()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select id, school_id from public.users where id = auth.uid() and role in ('teacher', 'hod', 'principal')
  ),
  docs as (
    select d.*
    from public.corpus_documents d, me
    where d.uploaded_by = me.id and d.superseded_at is null
  ),
  chunks as (
    select c.* from public.corpus_chunks c where c.document_id in (select id from docs)
  ),
  questions as (
    select q.* from public.generated_questions q where q.chunk_id in (select id from chunks)
  ),
  -- Sections this teacher owns, and whether each has approved material. A
  -- section with none is a class whose students currently have nothing.
  sections as (
    select
      cl.id,
      cl.section_name,
      co.subject,
      co.grade,
      exists (
        select 1
        from public.corpus_document_sections s
        join docs d2 on d2.id = s.document_id
        where s.class_id = cl.id and d2.status = 'approved'
      ) as has_material
    from public.classes cl
    join public.courses co on co.id = cl.course_id
    join me on me.id = cl.teacher_id
  ),
  -- Approved topics with no approved questions: a student can read the
  -- material but cannot practise it, which looks like a finished lesson and
  -- is not one.
  topics_without_questions as (
    select d.id, d.source_file
    from docs d
    where d.status = 'approved'
      and not exists (
        select 1 from public.generated_questions q2
        join public.corpus_chunks c2 on c2.id = q2.chunk_id
        where c2.document_id = d.id and q2.status = 'approved'
      )
  )
  select jsonb_build_object(
    'documents', jsonb_build_object(
      'total',    (select count(*) from docs),
      'approved', (select count(*) from docs where status = 'approved'),
      'pending',  (select count(*) from docs where status = 'pending'),
      'rejected', (select count(*) from docs where status = 'rejected')
    ),
    'sectionsLive', (select count(*) from chunks where approved_at is not null),
    'questions', jsonb_build_object(
      'approved', (select count(*) from questions where status = 'approved'),
      'pending',  (select count(*) from questions where status = 'pending'),
      'rejected', (select count(*) from questions where status = 'rejected')
    ),
    'byLevel', coalesce((
      select jsonb_agg(jsonb_build_object('level', level, 'count', n) order by level)
      from (select level, count(*)::int as n from questions where status = 'approved' group by level) x
    ), '[]'::jsonb),
    'byFormat', coalesce((
      select jsonb_agg(jsonb_build_object('format', kind, 'count', n) order by n desc)
      from (
        select coalesce(question->>'kind', 'unknown') as kind, count(*)::int as n
        from questions where status = 'approved' group by 1
      ) y
    ), '[]'::jsonb),
    'sections', coalesce((
      select jsonb_agg(jsonb_build_object(
        'section', section_name, 'subject', subject, 'grade', grade, 'hasMaterial', has_material
      ) order by subject, grade, section_name)
      from sections
    ), '[]'::jsonb),
    'topicsWithoutQuestions', coalesce((
      select jsonb_agg(jsonb_build_object('id', id, 'name', source_file) order by source_file)
      from topics_without_questions
    ), '[]'::jsonb),
    -- Twelve weeks of activity, zero-filled, so the shape of a gap is as
    -- visible as the shape of a burst.
    'weekly', coalesce((
      select jsonb_agg(jsonb_build_object('week', to_char(w, 'YYYY-MM-DD'), 'count', n) order by w)
      from (
        select w.week as w, (select count(*) from docs d where date_trunc('week', d.created_at) = w.week)::int as n
        from (
          select generate_series(
            date_trunc('week', now()) - interval '11 weeks',
            date_trunc('week', now()),
            interval '1 week'
          ) as week
        ) w
      ) z
    ), '[]'::jsonb)
  )
  where exists (select 1 from me);
$$;
revoke all on function public.teacher_analytics() from public, anon;
grant execute on function public.teacher_analytics() to authenticated;

-- public.teacher_asked_about — newest definition is 0030_concepts_and_questions.sql, which predates 0035.
create or replace function public.teacher_asked_about()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with mine as (
    select cl.id as class_id
    from public.classes cl
    join public.users me on me.id = auth.uid() and me.role in ('teacher', 'hod', 'principal')
    where cl.teacher_id = auth.uid()
  ),
  pupils as (
    select distinct u.id
    from public.class_enrollments e
    join mine on mine.class_id = e.class_id
    join public.users u on u.id = e.student_id and u.role = 'student'
  ),
  asks as (
    select
      c.id as conversation_id,
      c.student_id,
      coalesce(c.topic_title, 'Untitled lesson') as topic,
      count(*) filter (where t.intent in ('explain', 'example'))::int as help_presses
    from public.conversations c
    join pupils p on p.id = c.student_id
    join public.conversation_turns t on t.conversation_id = c.id and t.role = 'user'
    group by c.id, c.student_id, c.topic_title
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'topic', topic,
        'presses', total_presses,
        'students', students,
        -- The most any single student asked in one sitting. A mean hides the
        -- child who asked six times.
        'maxInOneSitting', max_presses,
        'repeatedStudents', repeated
      ) order by total_presses desc
    ),
    '[]'::jsonb
  )
  from (
    select
      topic,
      sum(help_presses)::int as total_presses,
      count(distinct student_id)::int as students,
      max(help_presses)::int as max_presses,
      count(distinct student_id) filter (where help_presses >= 3)::int as repeated
    from asks
    where help_presses > 0
    group by topic
  ) rolled;
$$;
revoke all on function public.teacher_asked_about() from public, anon;
grant execute on function public.teacher_asked_about() to authenticated;

-- public.teacher_class_codes — newest definition is 0027_class_material_names.sql, which predates 0035.
create or replace function public.teacher_class_codes()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select id from public.users where id = auth.uid() and role in ('teacher', 'hod', 'principal')
  )
  select coalesce(jsonb_agg(x order by x->>'subject', x->>'grade', x->>'section'), '[]'::jsonb)
  from (
    select jsonb_build_object(
      'classId', cl.id,
      'section', cl.section_name,
      'subject', co.subject,
      'grade', co.grade,
      'academicYear', co.academic_year,
      'code', (
        select j.code from public.class_join_codes j
        where j.class_id = cl.id and j.revoked_at is null
        order by j.created_at desc limit 1
      ),
      'students', (
        select count(*) from public.class_enrollments e where e.class_id = cl.id
      ),
      -- Approved and current only. A section whose one document is awaiting
      -- review, or has been superseded, is still a section whose students
      -- open the app to an empty page.
      --
      -- Titles rather than a count: "2 documents" tells a teacher they have
      -- not made a mistake; "Magnets and Electromagnets" tells them which
      -- mistake they have not made.
      'materials', coalesce((
        select jsonb_agg(regexp_replace(d.source_file, '\.[^.]+$', '') order by d.created_at desc)
        from public.corpus_document_sections ds
        join public.corpus_documents d on d.id = ds.document_id
        where ds.class_id = cl.id
          and d.status = 'approved'
          and d.superseded_at is null
      ), '[]'::jsonb)
    ) as x
    from public.classes cl
    join public.courses co on co.id = cl.course_id
    join me on me.id = cl.teacher_id
  ) rows;
$$;
revoke all on function public.teacher_class_codes() from public, anon;
grant execute on function public.teacher_class_codes() to authenticated;

-- public.teacher_question_outcomes — newest definition is 0031_reteach_approved_only.sql, which predates 0035.
create or replace function public.teacher_question_outcomes()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with mine as (
    select cl.id as class_id
    from public.classes cl
    join public.users me on me.id = auth.uid() and me.role in ('teacher', 'hod', 'principal')
    where cl.teacher_id = auth.uid()
  ),
  pupils as (
    select distinct u.id
    from public.class_enrollments e
    join mine on mine.class_id = e.class_id
    join public.users u on u.id = e.student_id and u.role = 'student'
  ),
  -- Approved only, and the filter lives HERE rather than at the end so a
  -- retired question's attempts never reach the per-question rollup and
  -- cannot inflate an attempts count that is then compared to the floor.
  live_questions as (
    select id from public.generated_questions where status = 'approved'
  ),
  tries as (
    select
      pa.generated_question_id as qid,
      pa.student_id,
      pa.answer,
      coalesce((pa.graded_result->>'correct')::boolean, false) as correct
    from public.practice_attempts pa
    join pupils p on p.id = pa.student_id
    join live_questions lq on lq.id = pa.generated_question_id
    where pa.generated_question_id is not null
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'questionId', q.id,
        'prompt', q.prompt,
        'level', q.level,
        'chunkId', c.id,
        'heading', coalesce(nullif(btrim(c.heading), ''), 'Untitled section'),
        'document', regexp_replace(d.source_file, '\.[^.]+$', ''),
        'attempts', s.attempts,
        'wrong', s.wrong,
        'students', s.students,
        'wrongAnswers', s.wrong_answers,
        'options', coalesce(q.question->'options', '[]'::jsonb)
      )
    ),
    '[]'::jsonb
  )
  from (
    select
      qid,
      count(*)::int as attempts,
      count(*) filter (where not correct)::int as wrong,
      count(distinct student_id)::int as students,
      coalesce(
        jsonb_object_agg(answer, n) filter (where answer is not null and n is not null),
        '{}'::jsonb
      ) as wrong_answers
    from (
      select
        t.qid,
        t.student_id,
        t.correct,
        case when not t.correct then t.answer end as answer,
        case when not t.correct then count(*) over (partition by t.qid, t.answer) end as n
      from tries t
    ) counted
    group by qid
  ) s
  join public.generated_questions q on q.id = s.qid
  join public.corpus_chunks c on c.id = q.chunk_id
  join public.corpus_documents d on d.id = c.document_id;
$$;
revoke all on function public.teacher_question_outcomes() from public, anon;
grant execute on function public.teacher_question_outcomes() to authenticated;
